### ISSUE TITLE
Inspector bug

### ISSUE THREAD

**Issue by valento92** [protyze/aframe-alongpath-component#5] opened 2017-01-26 18:29 UTC
I set inspect to true, and it's throwing some error on the console. Also, after setting a new path to the component it will go crazy. Console outputs:

```
aframe.js:62373 Uncaught (in promise) TypeError: Cannot read property 'isPlaying' of null
    at entityLoadCallback (aframe.js:62373)
    at emitLoaded (aframe.js:63198)
entityLoadCallback @ aframe.js:62373
emitLoaded @ aframe.js:63198
```

**Comment by protyze** [comment] 2017-07-10 10:56
Hi,

This might be fixed in the meantime. I could not reproduce it here: https://protyze.github.io/aframe-alongpath-component/basic/index.html

Let me know if still appears somewhere... I mean.. if this is still relevant for you ;)

**Closed by protyze** 2017-07-10 10:56 UTC
